cask_args appdir: '/Applications'

tap 'caskroom/cask' # DO I NEED THIS??? Holman didn't
tap 'homebrew/bundle'

##### START HOLMAN #####
# brew 'ack'
# brew 'coreutils'
# brew 'go'
# brew 'grc'
# brew 'imagemagick'
# brew 'jp2a'
# brew 'libcaca', args: ['with-imlib2']
# brew 'libgit2'
# brew 'openssl'
# brew 'node'
# brew 'readline'
# brew 'postgresql'
# brew 'ruby-build'
# brew 'rbenv'
# brew 'roundup'
# brew 'spaceman-diff'
# brew 'spark'
# brew 'unrar'
# brew 'wget'
# brew 'youtube-dl'
# 
# cask '1password'
# cask 'adium'
# cask 'firefox'
# cask 'garmin-express'
# cask 'google-chrome'
# cask 'handbrake'
# cask 'mapbox-studio'
# cask 'seashore'
# cask 'slack'
# cask 'steam'
# cask 'transmission'
# cask 'tunnelbear'
# cask 'vlc'
##### END HOLMAN #####

cask 'skitch'
cask 'evernote'
cask 'firefox'
cask 'google-chrome'
cask 'slack'
cask 'moom'

brew 'ack'
brew 'tig'
brew 'readline'
brew 'git-extras'
brew 'spaceman-diff'
brew 'the_silver_searcher'
brew 'ansiweather'
brew 'tmux'
